### ISSUE TITLE
同一个机场不同账号 只有一个今天突然成功

### ISSUE THREAD

**Issue by king0billy** [xiaocao666tzh/Airport-Checkin#11]
这个脚本之前用了快一年 两个月以前三个账号都突然开始出错，Error: Process completed with exit code 1
今天突然发现其中一个成功了，但是其他两个手动运行报错如下【需要的话我可以提供机场地址】

Run python3 ./main.py
  shell: /usr/bin/bash -e {0}
  env:
    RUN_ENV: prod
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:3).10.7/x6[4](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.7/x64/lib
    SCKEY: 
    EMAIL: ***
    PASSWORD: ***
    BASE_URL: ***
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 71[5](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:5), in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.7/x[6](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:6)4/lib/python3.10/site-packages/urllib3/connectionpool.py", line 46[7](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:7), in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 31[8](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:8), in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/requests/adapters.py", line 43[9](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:9), in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:10).7/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line [13](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:14)74, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Airport-Checkin/Airport-Checkin/./main.py", line 40, in <module>
    result = checkin()
  File "/home/runner/work/Airport-Checkin/Airport-Checkin/./main.py", line [16](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:17), in checkin
    session.get(base_url, verify=False)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/requests/sessions.py", line 5[42](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:43), in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/requests/adapters.py", line [49](https://github.com/king0billy/Airport-Checkin/actions/runs/6912712034/job/18808756102#step:6:50)8, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error: Process completed with exit code 1.

**Comment by king0billy** [comment]
成功的如下
![image](https://github.com/xiaocao666tzh/Airport-Checkin/assets/52921954/29680d0f-ab6d-4116-ae38-8a187d1108a8)
