### ISSUE TITLE
运行action出错，Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by mccrena** [xiaocao666tzh/Airport-Checkin#8]
完整代码如下：Run python3 ./main.py
Traceback (most recent call last):
  File "./main.py", line 36, in <module>
    sendurl = 'https://sctapi.ftqq.com/' + SCKEY + '.send?title=机场签到&desp=' + checkin()
  File "./main.py", line 30, in checkin
    response = json.loads(response.text)
  File "/opt/hostedtoolcache/Python/3.7.[13](https://github.com/mccrena/Airport-Checkin/runs/7702009112?check_suite_focus=true#step:6:14)/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
初步怀疑：是不是okgg.top这个网站不支持此签到，但是我看它确实是以SSP搭建的

**Comment by xiaocao666tzh** [comment]
应该是格式不同
